### ISSUE TITLE
Compilation failure under 4.04.0+flambda

### ISSUE THREAD

**Issue by hcarty** [OCamlPro/ocp-index#102]
Version 1.1.5 from opam, I haven't tested on vanilla 4.04.0:

```
$ opam install ocp-index
The following actions will be performed:
  ∗  install ocp-index 1.1.5

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[ERROR] The compilation of ocp-index failed at "make".

#=== ERROR while installing ocp-index.1.1.5 ===================================#
# opam-version 1.2.2
# os           darwin
# command      make
# path         /Users/hcarty/.opam/4.04.0+flambda/build/ocp-index.1.1.5
# compiler     4.04.0+flambda
# exit-code    2
# env-file     /Users/hcarty/.opam/4.04.0+flambda/build/ocp-index.1.1.5/ocp-index-63766-d2c37b.env
# stdout-file  /Users/hcarty/.opam/4.04.0+flambda/build/ocp-index.1.1.5/ocp-index-63766-d2c37b.out
# stderr-file  /Users/hcarty/.opam/4.04.0+flambda/build/ocp-index.1.1.5/ocp-index-63766-d2c37b.err
### stdout ###
# ocp-build -init
# ocp-build ocp-index-lib
### stderr ###
# [...]
# Error log:
# Error:
# [74.1] '/Users/hcarty/.opam/4.04.0+flambda/bin/ocamlc.opt' '-g' '-w' '+1..39-4-9-37-40' '-safe-string' '-bin-annot' '-c' '-o' '_obuild/3e53ee567b3938151d81cb153540cab7/indexScope.cmo' '-I' './_obuild/ocp-index-lib' '-I' './src' '-I' '/Users/hcarty/.opam/4.04.0+flambda/lib/ocp-indent/utils' '-I' '/Users/hcarty/.opam/4.04.0+flambda/lib/ocaml/compiler-libs' '-I' '/Users/hcarty/.opam/4.04.0+flambda/lib/ocp-indent/lexer' 'src/indexScope.ml'
#
# File "src/indexScope.ml", line 24, characters 14-26:
# Error: Unbound module Pos
#
# Error:
# Target _obuild/ocp-index-lib/indexScope.cmo not built
# make: *** [ocp-index-lib] Error 2



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
The following actions failed
  ∗  install ocp-index 1.1.5
No changes have been performed
```

**Comment by AltGr** [comment]
ocp-index 1.1.5 works with 4.04.0 ; the error, here, doesn't seem to be related with the OCaml version.
Package `Pos` is supposed to come from `ocp-indent`'s parser modules, that `ocp-index` uses. Can you check what version is installed and if the installation seems consistent ?

Thanks!

**Comment by AltGr** [comment]
I found your branch at `git+https://github.com/hcarty/ocp-indent#sequence-ignore-extensions` is based upon ocp-indent's master, and the package was still probably pinned on your side.
Current version on opam-repository is actually based upon the branch `rewind`, because we found some regression with @OCamlPro-Henry's new parser ; ocp-indent hasn't been ported to the `master` version yet. Unfortunately, @OCamlPro-Henry has been very busy recently and couldn't fix the regressions yet so that we complete the update.

**Comment by hcarty** [comment]
Ah!  Thank you very much - you're correct, I still had a version pinned based off of `master`.

**Comment by romildo** [comment]
I am getting this error too when compiling `ocp-index-1.1.5` with `ocp-indent-1.6.0` on NixOS:

```
0.01s _obuild/ocp-index-lib/indexScope.cmo                             [failed]
[74.1] Command failed: '/nix/store/qvrkhhxmg9sl284f2b0asxhb37fw75yl-ocaml-4.04.1/bin/ocamlc.opt' '-g' '-w' '+1..39-4-9-37-40' '-safe-string' '-bin-annot' '-c' '-o' '_obuild/5b757095a3f03a9407098f7ce1bbd117/indexScope.cmo' '-I' './_obuild/ocp-index-lib' '-I' './src' '-I' '/nix/store/qvrkhhxmg9sl284f2b0asxhb37fw75yl-ocaml-4.04.1/lib/ocaml/compiler-libs' '-I' '/nix/store/3rv464qci8cxwvdlqxdna2x1h8amlk0w-ocp-indent-1.6.0/lib/ocaml/4.04.1/site-lib/ocp-indent/utils' '-I' '/nix/store/3rv464qci8cxwvdlqxdna2x1h8amlk0w-ocp-indent-1.6.0/lib/ocaml/4.04.1/site-lib/ocp-indent/lexer' './src/indexScope.ml'
-- stderr for ./_obuild/ocp-index-lib/indexScope.cmo --
File "./src/indexScope.ml", line 24, characters 14-26:
Error: Unbound module Pos
```
